# Generated by Django 3.0.1 on 2020-01-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCBuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='type',
            field=models.CharField(default='X', max_length=256, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
