# Generated by Django 3.0.1 on 2020-01-07 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PCBuilder', '0003_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalproduct',
            old_name='category',
            new_name='cat',
        ),
    ]
