# Generated by Django 3.0.1 on 2020-01-07 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PCBuilder', '0004_auto_20200107_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalproduct',
            old_name='cat',
            new_name='category',
        ),
    ]
