# Generated by Django 3.0.1 on 2020-01-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCBuilder', '0007_auto_20200107_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Amount')),
            ],
        ),
    ]
